package com.publiccms.entities.sys;
// Generated 2025-3-11 20:29:09 by Hibernate Tools 5.6.15.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.publiccms.common.generator.annotation.GeneratorColumn;

/**
 * SysWorkflowProcessItem generated by hbm2java
 */
@Entity
@Table(name = "sys_workflow_process_item")
public class SysWorkflowProcessItem implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private SysWorkflowProcessItemId id;
    /**
     * process id
     * <p>
     * 流程id
     */
    @GeneratorColumn(title = "流程")
    private long processId;

    public SysWorkflowProcessItem() {
    }

    public SysWorkflowProcessItem(SysWorkflowProcessItemId id, long processId) {
        this.id = id;
        this.processId = processId;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "itemType", column = @Column(name = "item_type", nullable = false, length = 50)),
            @AttributeOverride(name = "itemId", column = @Column(name = "item_id", nullable = false, length = 100)) })
    public SysWorkflowProcessItemId getId() {
        return this.id;
    }

    public void setId(SysWorkflowProcessItemId id) {
        this.id = id;
    }

    @Column(name = "process_id", nullable = false)
    public long getProcessId() {
        return this.processId;
    }

    public void setProcessId(long processId) {
        this.processId = processId;
    }

}
