name: Docker Image CI

on:
  push:
    branches: [ "V5" ]
  pull_request:
    branches: [ "V5" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup JDK 11
      uses: actions/setup-java@v3.14.1
      with: 
        java-version: '11'
        
    - name: Build with Maven
      run: mvn -Dbasedir=publiccms-parent clean package
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.10.0

    - name: login docker
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5.7.0
      with:
        images: sanluan/PublicCMS
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v6.16.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    
